import type { ThemePackage } from '@/types';

/**
 * 内置聊天气泡主题包。
 * 渲染器由 src/themes/chatBubble/renderers 提供。
 *
 * 每套主题的可调参数（schema）驱动后台「聊天气泡主题」面板表单，
 * 渲染器把这些参数映射成聊天里左右气泡的实际配色。
 */
export const BUILTIN_CHAT_BUBBLE_THEMES: ThemePackage[] = [
  {
    id: 'chat-bubble-ios',
    name: 'iOS 蓝',
    version: '1.0.0',
    author: 'XinBlog',
    description: '经典的 iOS iMessage 风格：自己蓝色、对方灰白，圆角柔和。',
    previewImage: '',
    minAppVersion: '1.0.0',
    components: {
      postCard: { variant: 'default' },
      chatBubble: {
        variant: 'ios',
        params: {
          mineBg: '#38b6ff',
          mineText: '#ffffff',
          otherBg: '#f0f2f5',
          otherText: '#2f3542',
          radius: 18,
          imageRadius: 12,
          mineSharpCorner: 'top-right',
          otherSharpCorner: 'top-left',
        },
        schema: [
          { key: 'mineBg', label: '自己气泡背景色', type: 'color' },
          { key: 'mineText', label: '自己文字颜色', type: 'color' },
          { key: 'otherBg', label: '对方气泡背景色', type: 'color' },
          { key: 'otherText', label: '对方文字颜色', type: 'color' },
          { key: 'radius', label: '气泡圆角', type: 'number', min: 4, max: 28, step: 1 },
          { key: 'imageRadius', label: '图片圆角', type: 'number', min: 4, max: 28, step: 1 },
          {
            key: 'mineSharpCorner',
            label: '自己气泡尖角位置',
            type: 'select',
            options: [
              { value: 'top-right', label: '右上' },
              { value: 'top-left', label: '左上' },
              { value: 'bottom-right', label: '右下' },
              { value: 'bottom-left', label: '左下' },
            ],
          },
          {
            key: 'otherSharpCorner',
            label: '对方气泡尖角位置',
            type: 'select',
            options: [
              { value: 'top-left', label: '左上' },
              { value: 'top-right', label: '右上' },
              { value: 'bottom-left', label: '左下' },
              { value: 'bottom-right', label: '右下' },
            ],
          },
        ],
      },
    },
  },
  {
    id: 'chat-bubble-gradient',
    name: '渐变彩色',
    version: '1.0.0',
    author: 'XinBlog',
    description: '渐变底色 + 明亮文字，活泼鲜明的社交氛围。',
    previewImage: '',
    minAppVersion: '1.0.0',
    components: {
      postCard: { variant: 'default' },
      chatBubble: {
        variant: 'gradient',
        params: {
          mineStart: '#ff7e5f',
          mineEnd: '#feb47b',
          mineText: '#ffffff',
          otherStart: '#ffe9da',
          otherEnd: '#ffd1e8',
          otherText: '#7a4a3b',
          radius: 20,
          imageRadius: 14,
          mineSharpCorner: 'top-right',
          otherSharpCorner: 'top-left',
        },
        schema: [
          { key: 'mineStart', label: '自己渐变起始色', type: 'color' },
          { key: 'mineEnd', label: '自己渐变结束色', type: 'color' },
          { key: 'mineText', label: '自己文字颜色', type: 'color' },
          { key: 'otherStart', label: '对方渐变起始色', type: 'color' },
          { key: 'otherEnd', label: '对方渐变结束色', type: 'color' },
          { key: 'otherText', label: '对方文字颜色', type: 'color' },
          { key: 'radius', label: '气泡圆角', type: 'number', min: 4, max: 28, step: 1 },
          { key: 'imageRadius', label: '图片圆角', type: 'number', min: 4, max: 28, step: 1 },
          {
            key: 'mineSharpCorner',
            label: '自己气泡尖角位置',
            type: 'select',
            options: [
              { value: 'top-right', label: '右上' },
              { value: 'top-left', label: '左上' },
              { value: 'bottom-right', label: '右下' },
              { value: 'bottom-left', label: '左下' },
            ],
          },
          {
            key: 'otherSharpCorner',
            label: '对方气泡尖角位置',
            type: 'select',
            options: [
              { value: 'top-left', label: '左上' },
              { value: 'top-right', label: '右上' },
              { value: 'bottom-left', label: '左下' },
              { value: 'bottom-right', label: '右下' },
            ],
          },
        ],
      },
    },
  },
  {
    id: 'chat-bubble-minimal',
    name: '极简边框',
    version: '1.0.0',
    author: 'XinBlog',
    description: '黑白极简：无填充底色，仅靠细边框区分对话双方。',
    previewImage: '',
    minAppVersion: '1.0.0',
    components: {
      postCard: { variant: 'default' },
      chatBubble: {
        variant: 'minimal',
        params: {
          mineBorder: '#ff8a65',
          mineText: '#ff7043',
          otherBorder: '#9aa0a6',
          otherText: '#5f6368',
          radius: 12,
          imageRadius: 8,
          mineSharpCorner: 'top-right',
          otherSharpCorner: 'top-left',
        },
        schema: [
          { key: 'mineBorder', label: '自己气泡边框颜色', type: 'color' },
          { key: 'mineText', label: '自己文字颜色', type: 'color' },
          { key: 'otherBorder', label: '对方气泡边框颜色', type: 'color' },
          { key: 'otherText', label: '对方文字颜色', type: 'color' },
          { key: 'radius', label: '气泡圆角', type: 'number', min: 4, max: 28, step: 1 },
          { key: 'imageRadius', label: '图片圆角', type: 'number', min: 4, max: 28, step: 1 },
          {
            key: 'mineSharpCorner',
            label: '自己气泡尖角位置',
            type: 'select',
            options: [
              { value: 'top-right', label: '右上' },
              { value: 'top-left', label: '左上' },
              { value: 'bottom-right', label: '右下' },
              { value: 'bottom-left', label: '左下' },
            ],
          },
          {
            key: 'otherSharpCorner',
            label: '对方气泡尖角位置',
            type: 'select',
            options: [
              { value: 'top-left', label: '左上' },
              { value: 'top-right', label: '右上' },
              { value: 'bottom-left', label: '左下' },
              { value: 'bottom-right', label: '右下' },
            ],
          },
        ],
      },
    },
  },
  {
    id: 'chat-bubble-ticket',
    name: '票据',
    version: '1.0.0',
    author: 'XinBlog',
    description: '入场票据风：暖米底 + 撕边虚线描边，刷卡验票感。',
    previewImage: '',
    minAppVersion: '1.0.0',
    components: {
      postCard: { variant: 'default' },
      chatBubble: { variant: 'ticket', params: {} },
    },
  },
  {
    id: 'chat-bubble-neon',
    name: '霓虹',
    version: '1.0.0',
    author: 'XinBlog',
    description: '赛博霓虹：深底 + 彩色外发光晕，夜店氛围。',
    previewImage: '',
    minAppVersion: '1.0.0',
    components: {
      postCard: { variant: 'default' },
      chatBubble: { variant: 'neon', params: {} },
    },
  },
  {
    id: 'chat-bubble-glass',
    name: '玻璃',
    version: '1.0.0',
    author: 'XinBlog',
    description: '玻璃拟态：半透明磨砂 + 通透内光，现代轻盈。',
    previewImage: '',
    minAppVersion: '1.0.0',
    components: {
      postCard: { variant: 'default' },
      chatBubble: { variant: 'glass', params: {} },
    },
  },
  {
    id: 'chat-bubble-jelly',
    name: '果冻',
    version: '1.0.0',
    author: 'XinBlog',
    description: '果冻渐变：上浅下深的 Q 弹色泽，甜甜圈质感。',
    previewImage: '',
    minAppVersion: '1.0.0',
    components: {
      postCard: { variant: 'default' },
      chatBubble: { variant: 'jelly', params: {} },
    },
  },
  {
    id: 'chat-bubble-sticky',
    name: '手账',
    version: '1.0.0',
    author: 'XinBlog',
    description: '手账便签：浅色底 + 右下折角 + 轻投影。',
    previewImage: '',
    minAppVersion: '1.0.0',
    components: {
      postCard: { variant: 'default' },
      chatBubble: { variant: 'sticky', params: {} },
    },
  },
  {
    id: 'chat-bubble-dark',
    name: '酷黑',
    version: '1.0.0',
    author: 'XinBlog',
    description: '暗夜反转：近黑实底 + 亮字，高对比昼夜分明。',
    previewImage: '',
    minAppVersion: '1.0.0',
    components: {
      postCard: { variant: 'default' },
      chatBubble: { variant: 'dark', params: {} },
    },
  },
  {
    id: 'chat-bubble-candy',
    name: '糖果',
    version: '1.0.0',
    author: 'XinBlog',
    description: '糖果撞色：高饱和实底 + 白字，明快童趣。',
    previewImage: '',
    minAppVersion: '1.0.0',
    components: {
      postCard: { variant: 'default' },
      chatBubble: { variant: 'candy', params: {} },
    },
  },
  {
    id: 'chat-bubble-mint',
    name: '薄荷',
    version: '1.0.0',
    author: 'XinBlog',
    description: '薄荷清爽：低饱和薄荷绿/奶油，马卡龙柔和。',
    previewImage: '',
    minAppVersion: '1.0.0',
    components: {
      postCard: { variant: 'default' },
      chatBubble: { variant: 'mint', params: {} },
    },
  },
  {
    id: 'chat-bubble-marble',
    name: '石纹',
    version: '1.0.0',
    author: 'XinBlog',
    description: '理石质感：近白底 + 淡灰斑驳纹理，低调高级。',
    previewImage: '',
    minAppVersion: '1.0.0',
    components: {
      postCard: { variant: 'default' },
      chatBubble: { variant: 'marble', params: {} },
    },
  },
  {
    id: 'chat-bubble-gingko',
    name: '描边',
    version: '1.0.0',
    author: 'XinBlog',
    description: '渐变描边：透明底 + 双色渐变轮廓，轻透优雅。',
    previewImage: '',
    minAppVersion: '1.0.0',
    components: {
      postCard: { variant: 'default' },
      chatBubble: { variant: 'gingko', params: {} },
    },
  },
];